version: '3.4'

networks:
  demoapp:

services:
  appdb:
    hostname: sql2
    container_name: test-storemvc-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433 # 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=myMegaBoomBoomPassword12345!!!
    networks:
      - demoapp
  storemvc:
    container_name: test-storemvc
    image: ${DOCKER_REGISTRY-}storemvc
    build:
      context: .
      dockerfile: StoreMVC/Dockerfile
    ports:
      - 8001:80
    depends_on:
      - appdb
    environment:
      - DB_HOST=appdb
      - DB_NAME=StoreMVC_Auth_db
      - DB_MSSQL_SA_PASSWORD=myMegaBoomBoomPassword12345!!!
    networks:
      - demoapp